spring:
  datasource: #數據源
    type:  com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/exchange?characterEncoding=utf8&serverTimeZone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true

mybatis:
  mapper-locations: classpath*:com/zxd/inter/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

